# Generated by Django 6.1 on 2026-08-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Унікальна назва')),
                ('title', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('image', models.CharField(max_length=50, verbose_name='Фото товару')),
                ('desc', models.TextField(verbose_name='Опис товару')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ціна')),
            ],
        ),
    ]
